[General]
__userfile__=true
iconTheme=Papirus-Dark
panels=panel1
panels=panel1

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\x1\xff\xff\x1c\x1c\x1c\x1c\x1c\x1c\0\0)
background-image=
font-color=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0)
hidable=false
iconSize=28
lineCount=1
lockPanel=false
opacity=90
panelSize=40
plugins=mainmenu, quicklaunch, taskbar, spacer, tray, worldclock, showdesktop
position=Bottom
reserve-space=true
show-delay=0
width=100
width-percent=true

[mainmenu]
type=mainmenu
icon=/usr/share/icons/Papirus-Dark/32x32/apps/steam.svg
showText=false

[quicklaunch]
type=quicklaunch
apps\1\desktop=/usr/share/applications/steamdeck-steam.desktop
apps\2\desktop=/usr/share/applications/steamdeck-bigpicture.desktop
apps\3\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\4\desktop=/usr/share/applications/qterminal.desktop
apps\size=4

[taskbar]
type=taskbar
buttonStyle=IconAndText
groupingEnabled=false
showGroupOnHover=true

[spacer]
type=spacer

[tray]
type=tray

[worldclock]
type=worldclock

[showdesktop]
type=showdesktop
